server:
  port: 8081
spring:
  cloud:
    discovery:
      enabled: true
  application:
    name: client-service
  datasource:
    url: jdbc:h2:mem:bank-db
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
